support quote strings
RedisGraph/redisgraph-py pull request #125
Opened 2021-05-13 12:25 UTC by AvitalFineRedis

2021-05-16 08:17 UTC, chayim commented on redisgraph/util.py
> +    return '"' + v + '"'
return '"{}"'.format(v)

2021-05-30 07:33 UTC, chayim requested changes
@gkorland Can you remove the .idea folder. We shouldn't include IDE settings in our source. The rest is approved.

2021-05-30 09:30 UTC, gkorland approved these changes

2021-05-30 09:35 UTC, chayim approved these changes

2021-05-30 09:49 UTC, merged